//import Components
import UploadButton from "../components/upload-button";
import PluginChoice from "./plugin-choice";

export default function MainHeader({
  PluginSelected,
  ChangeHandler,
  SetWordPressPlugin,
  sendError,
}) {
  return (
    <div
      id="header"
      className="min-h-[300px] bg-dark-purple text-white border-b-2 border-white py-7 mb-7 md:pt-10 md:pb-20"
    >
      <div className="flex flex-wrap items-center px-5">
        <div className="md:max-w-1/2 md:p-[5%]">
          <h1 className="font-source-sans font-bold text-2xl mb-2 md:mb-4 md:text-4xl">
            Convert Your WordPress Redirects from RankMath or YoastSEO to Next.js
          </h1>
          <p className="font-montserrat mb-4">
            This tool helps you convert redirects generated by the{" "}
            <a
              href="https://wordpress.org/plugins/wordpress-seo/"
              title="Yoast SEO Plugin"
              className="font-bold"
            >
              YoastSEO
            </a>{" "}
            or{" "}
            <a
              href="https://wordpress.org/plugins/seo-by-rank-math/"
              title="RankMath SEO Plugin"
              className="font-bold"
            >
              RankMath
            </a>{" "}
            plugins into a format compatible with your{" "}
            <a
              href="https://nextjs.org"
              title="Next.js Framework"
              className="font-bold"
            >
              Next.js
            </a>{" "}
            application. Check the documentation for detailed instructions on how to use this tool.
          </p>
          <ol className="font-montserrat pl-7 list-decimal mb-5">
            <li>Export redirects from your SEO plugin</li>
            <li>Upload the exported .csv file here</li>
            <li>This tool will convert your redirects into readable code</li>
            <li>Paste the converted code into your next.config.js file</li>
          </ol>
        </div>
        <div className="md:max-w-1/2 md:p-[5%]">
          <div className="flex flex-wrap flex-col justify-center text-black bg-white p-[5%] md:min-h-full rounded-lg md:py-16">
            <h2 className="font-montserrat text-lg font-bold md:text-xl">
              Step 1: Select Your SEO Plugin!
            </h2>
            <p className="font-source-sans text-sm mb-2">
              <b>Note:</b> This tool currently does not support converting{" "}
              <a className="italic underline text-rosa ease-linear transition-colors hover:bg-rosa hover:text-white" href="https://yoast.com/help/what-are-regex-redirects/" title="Example of regex rules">
                regex rules
              </a>{" "}
              from your WordPress plugin. Please ensure you upload a .csv file.
            </p>
            <PluginChoice SetWordPressPlugin={SetWordPressPlugin} />
            <h2 className="font-montserrat text-lg font-bold md:text-xl">
              Step 2: Upload Redirects Export!
            </h2>
            <UploadButton
              ChangeHandler={ChangeHandler}
              PluginSelected={PluginSelected}
              sendError={sendError}
            />
            <p className="font-source-sans text-sm mb-7">
              * No data will be stored on our servers.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
