import Head from "next/head";

export default function howtouse() {
  return (
    <div>
      <Head>
        <title>
          How to convert Redirects from WordPress to next.js - Wp To NextJS
        </title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta
          name="description"
          content="Convert your WordPress redirects generated by RankMath or YoastSEO to next.js in seconds with wpToNext. Learn how to use our tool now!"
        />
      </Head>

      <div className="bg-dark">
        <div className="max-w-7xl mx-auto flex flex-wrap items-center px-5 py-8 md:py-16 border-b border-white">
          <div className="mb-7 md:max-w-1/2 md:mb-0 md:pr-[5%]">
            <h1 className="font-source-sans font-bold text-2xl text-white md:text-4xl">
              How to use Wp To NextJS
            </h1>
            <p className="font-montserrat text-white">
              This free tool was created for website owners who have decided to
              migrate their WordPress websites to next.js or use next.js in
              conjunction with WordPress.
            </p>
            <p className="font-montserrat text-white mt-4">
              Follow these steps to set up redirects in next.js:
            </p>
            <ol className="font-montserrat text-white mt-4 list-decimal list-inside">
              <li>
                Export your redirects from WordPress using plugins like RankMath
                or YoastSEO.
              </li>
              <li>
                Use the wpToNext tool to automatically convert these WordPress
                redirects into next.js compatible format.
              </li>
              <li>
                Once converted, copy the generated redirects and paste them into
                the `next.config.js` file of your next.js project under the
                redirects configuration section.
              </li>
              <li>
                Ensure the redirects are written in the following format:
                <pre className="bg-gray-800 text-white p-4 rounded mt-4">
                  {`{
                    source: "/old-url",
                    destination: "/new-url",
                    permanent: true
                  }`}
                </pre>
              </li>
              <li>
                After adding your redirects, restart your next.js server, and
                the redirects will be applied automatically.
              </li>
            </ol>
          </div>
          <div className="w-full md:max-w-1/2">
            <a
              href="https://nextjs.org/docs/api-reference/next.config.js/redirects"
              target="_blank"
              rel="noopener norefferer"
              className="font-montserrat font-light text-white text-sm text-center"
            >
              Learn more about next.js redirects in the official documentation
            </a>
          </div>
        </div>
      </div>

      <div className="bg-dark">
        <div className="max-w-6xl mx-auto py-16 px-5">
          <div className="bg-dark-purple min-w-full border border-white rounded-lg py-4 mb-4 md:py-10 md:mb-10">
            <div className="flex flex-wrap gap-5 items-center p-5 md:p-30">
              <div className="md:max-w-[40%]">
                <h2 className="font-source-sans font-bold text-4xl text-white mb-5">
                  Why should you migrate your WordPress redirects to next.js?
                </h2>
              </div>
              <div className="md:max-w-[55%]">
                <p className="font-montserrat text-white mb-4">
                  In search engine optimization, redirects are essential to
                  ensure that both users and search engines can find your
                  content even if it's moved to a new URL.
                  <span className="bg-rosa">
                    Otherwise, loss in traffic or rankings can occur.
                  </span>
                </p>

                <p className="font-montserrat text-white mb-4">
                  When you migrate to next.js, bringing your existing redirects
                  is important to maintain your SEO performance. By converting
                  WordPress redirects into next.js compatible format, you can
                  ensure smooth user experience and SEO benefits during the
                  transition.
                </p>
                <a
                  href="https://www.searchenginejournal.com/ranking-factors/301-redirects/"
                  title="Search Engine Journal about 301 redirects"
                >
                  <div className="font-source-sans text-white text-center bg-rosa py-4 px-6 mb-2 rounded-md min-w-full transition-colors ease-linear hover:bg-dark hover:border border-white md:min-w-[22%] md:mb-0">
                    Learn more about how Google handles redirects
                  </div>
                </a>
              </div>
            </div>
          </div>

          <div className="min-w-full py-10 mb-4 md:mb-10">
            <div className="flex flex-wrap items-center md:p-30 border border-white rounded-lg md:border-0 md:rounded-none">
              <div className="bg-dark-purple md:max-w-1/2 order-1 border-0 md:border md:border-white md:rounded-lg p-5 md:p-10 md:-mr-8 md:z-20">
                <h2 className="font-source-sans font-bold text-4xl text-white mb-2 md:mb-4">
                  Yoast SEO vs RankMath - Which SEO Plugin is better?
                </h2>
                <a
                  href="https://raidboxes.io/en/blog/online-marketing/wordpress-seo-plugins/"
                  title="Yoast SEO and RankMath for WordPress compared"
                >
                  <div className="font-source-sans text-white text-center bg-rosa py-4 px-6 mb-2 rounded-md min-w-full transition-colors ease-linear hover:bg-dark hover:border border-white md:min-w-[22%] md:mb-0">
                    Read the full post
                  </div>
                </a>
              </div>
              <div className="bg-dark-purple md:max-w-1/2 md:bg-dark order-2 border-0 md:border md:border-white rounded-lg p-5 md:p-16 md:z-10">
                <p className="font-montserrat text-white">
                  Yoast SEO and RankMath are the two most popular solutions for
                  optimizing your WordPress Website for search engines. Both are
                  free and offer similar functionality. To help you decide which
                  one is better for your site, check out our comprehensive
                  guide.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
